name: Symbiotest

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  
jobs: 
  test-infra-action:
      runs-on: ubuntu-latest
  
      steps:
        - uses: actions/checkout@v4
  
        - name: Scan
          uses: SymbioticSec/actions/scan@v0.1.2
          with:
            scan-type: code
            api-token: ${{ secrets.SYMBIOTIC_ORGA_TOKEN }}
